spring:
  cloud:
    gateway:
      routes:
        - id: SERVICE-USER
          uri: lb://SERVICE-USER
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=0

        - id: SERVICE-ADMIN
          uri: lb://SERVICE-ADMIN
          predicates:
            - Path=/admin-service/**
          filters:
            - StripPrefix=0
            - CustomPrePostFilter

        - id: SERVICE-CONTACT
          uri: lb://SERVICE-CONTACT
          predicates:
            - Path=/contact-service/**
          filters:
            - StripPrefix=0

        - id: SERVICE-AUTH
          uri: lb://SERVICE-AUTH
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=0
            - CustomPrePostFilter

  boot:
    admin:
      client:
        url: http://localhost:5051
        password: adm123
        username: springAdmin

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:1010/eureka/

server:
  port: 5050

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
   urls:
     - name: Service User
       url: /user-service/v3/api-docs
     - name: Service Admin
       url: /admin-service/v3/api-docs
     - name: Service Contact
       url: /contact-service/v3/api-docs
     - name: Service Auth
       url: /auth-service/v3/api-docs
